name: CI for PR Merge
on:
  pull_request:
    branches: [main]
jobs:
  default_settings:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Configure Bazel
        uses: ./
        with:
          disk_cache: "true"
      - name: Test the Workspace
        shell: bash
        run: |
          cd ci
          bazel test //...
      - name: Verify ci config enabled
        shell: bash
        run: |
          grep -q 'common --config=ci' ~/.bazelrc || \
            (echo >&2 "Expected --config=ci in ~/.bazelrc" && exit 1)
      - name: Verify output_base override removed
        shell: bash
        run: |
          if grep -q 'startup --output_base=' ~/.bazelrc; then
            echo >&2 "Expected output_base override to be removed"
            exit 1
          fi
  ci_config_disabled:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Configure Bazel
        uses: ./
        with:
          enable_ci_config: "false"
      - name: Test the Workspace
        shell: bash
        run: |
          cd ci
          bazel test //...
      - name: Verify ci config not present
        shell: bash
        run: |
          if grep -q 'common --config=ci' ~/.bazelrc; then
            echo >&2 "Expected --config=ci to NOT be in ~/.bazelrc"
            exit 1
          fi
  all_ci_tests:
    runs-on: ubuntu-22.04
    needs:
      - default_settings
      - ci_config_disabled
    if: ${{ always() }}
    steps:
      - uses: cgrindel/gha_join_jobs@605424defceef3181c9fde3df903ea8ec35e267a # v1.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
