name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu_ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Configure Bazel
      uses: ./
      with:
        repo_name: gha_set_up_bazel_ci
        bazel_repo_cache_dir: ~/.cache/custom_bazel_repo
        bazel_disk_cache_dir: ~/.cache/custom_bazel_disk
        workspace_dir: ci
    
    - name: Test the Workspace
      shell: bash
      run: |
        cd ci
        bazel test //...

    - name: Test Output
      shell: bash
      run: |
        echo "Repo Cache"
        tree ~/.cache/custom_bazel_repo
        [[ -d ~/.cache/custom_bazel_repo/content_addressable ]] || \
          (echo >&2 "Expected data to be in the repo cache." && exit 1)
        echo "Disk Cache"
        tree ~/.cache/custom_bazel_disk
        [[ -d ~/.cache/custom_bazel_disk/ac ]] || \
          (echo >&2 "Expected data to be in the disk  cache." && exit 1)

